name: Run checks on each commit.
on: pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup node.js environment
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version-file: '.node-version'
      #     cache: 'yarn'

      # assignee_count=$(cat ${{ github.event_path }} | jq '.pull_request.assignees')

      - name: Set Assignee
        run: |
          assignee_count=$(cat ${{ github.event_path }})
          assignee_count_pr=$(jq '.pull_request.assignees')
          assignee_count_len=$(jq '.pull_request.assignees | length')
          echo "Assignee count: $assignee_count"
          echo "Assignee count PR: $assignee_count_pr"
          echo "Assignee count with length: $assignee_count_len"

      # - name: Group of log lines
      #   run: |
      #     echo "::group::My title"
      #     echo "Inside group"
      #     echo "::endgroup::"

      # - name: Install packages
      #   run: yarn install --frozen-lockfile

      # - name: Lint
      #   run: yarn lint
