name: Run checks on each commit.
on: pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup node.js environment
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version-file: '.node-version'
      #     cache: 'yarn'

      - name: Set Assignee
        run: |
          assignee_count=$(cat ${{ github.event_path }} | jq '.pull_request.assignees)
          cat assignee_count

      # - name: Install packages
      #   run: yarn install --frozen-lockfile

      # - name: Lint
      #   run: yarn lint
